name: docs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Cancel concurrent flows on PRs
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup doc dependencies
        run: |
          pip install -f docs/requirements.txt
      
      - name: Build docs
        run: |
          cd docs
          make html

  apidocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup doc dependencies
        run: |
          pip install -f apidocs/requirements.txt
          pip install -e .
      
      - name: Build docs
        run: |
          cd apidocs
          make html